language: android
jdk: oraclejdk8
before_cache:
- cd ${TRAVIS_BUILD_DIR}/gradle/caches/
- find . -name "*.lock" -exec rm -rfv {} \;
- cd ${TRAVIS_BUILD_DIR}
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
env:
  global:
  - secure: NLrjPLXi+orN+nmb+CZ0ny3SSghk/2vGNVh0XNqqJ/Yq6brWtOFo29M9FThK6W6FSNWx/YKcV9YLDmQuDzHHoez1zi7MVpQ0CDVgrpoCQpuMu2DDI2lki1ovvbPmc0XOjYJ+TomDvU2o1Qzg9Gvteh4XNIzEObSnhV/ABFpugqEKR3pvSSCyBZHnvqANWy/Ng6bAJtt82aziDVvayw+hgwAluvdprljy9OmYoCI7guwGzJSbgaH2z4PnGthPEtM9X5A+tnU4hGRmMDP4WXM3uxaBYqqXfOVwL/e3hcSJoheXdyhT/2RDpK6bDVPxy9+nxu6cGez05hRcB7J3DYaFmpjnRL6WtDdC7m63pRzs1i7o+NQ3JYMFQsQgXAOboY7omYOBU9sn1O1y8BggebaRLporW3Y9b/2eXpYdqSaPu9mmhrEu38AG+kyQNkc1gb15+RW5oKghTDrJRSuWeTuXV8neAKelJDtLWOtlgSfvotaPJl3ypey0KG4dZFKfE/ir9CsFklwRbrhw0WbP3rB/z5d1+mwCyTvLLcjeO7vAHPVN/Q0FkOvRcd4MZIFvRsGi5EQO3LsS+27utP/m8gKdYEvP5y+qKf/R/+JZ0xRdThzGvRiUcxrohVUkUyXvqM5Y+FxgOWItdrLBb8aJ16BLJtFF4UkHBF5teZ6jWUCdJN8=
notifications:
  email: false
android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - tools
install:
- openssl aes-256-cbc -K $encrypted_903a93ed2309_key -iv $encrypted_903a93ed2309_iv
  -in keystore.enc -out keystore -d
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- "./gradlew --version"
- sdkmanager --list || true
script:
- "./gradlew clean build"
- "./gradlew test"
after_script:
- cat ${TRAVIS_BUILD_DIR}/*/build/reports/lint-results.xml
before_deploy:
- cp $TRAVIS_BUILD_DIR/keystore $HOME
- cd mobile/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore
  -storepass $storepass mobile-release-unsigned.apk sign
- jarsigner -verify mobile-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/25.0.2/zipalign -v 4 mobile-release-unsigned.apk mobile-release.apk"
deploy:
  provider: releases
  prerelease: true
  file: mobile-release.apk
  skip_cleanup: true
  on:
    repo: digitaldan/openhab.android
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: DgfPKGvRD9BEUHw8749KWEwm/huLK8o4B0Iol0ShQ49L8+XOp+2lIDeJOzgMWnAFh3IWGQqQmh3XEl5JJe4bb1USAksHxCsfUU6OukSiSPXoIAnURfDAURLBUboBGf7bsQKdwpXfJogRKAETmUW/yTxJidNBS0q+yuEqMgLPcS0HDQHQacz0OYWqumlfhCBH/NyDIosCcSsXnxrYCYbFh+hZ1NpgTWvOmPEVg6sBgTGT5CCFwG5Ctvum50zIQyq80Q7kSzwA85ePlE5fmnmIK5tBcRP8w9XFYoEs+A5866Lb/DDhFMGqlNdKzr43bE6wnFEpB75nZzMKmRpP5QEhSN1kM8WNREWj00WW+XXV4JLiGprRAf7zaDFnJtfaQ24F8Kn0HsdpPf32d0kaMuanIs57P8dU7MUXZlMj3z6vGwVis0TvcsIfCypQwiaYDH6uEwHZ0aUYHiFsJio0Rv+XoI5LxWIjUit3M7ItjO6B4oy7xgJG/zxb4RjYN3VaMTBPk0mkztSXQ2RHuhZl8gJElsdWqREdblI+ku85RCAnucNweqxwvp/e5bcFCCspq5q3SKoakvMQc261MI0tHapkoowkigan6czl2IXhUv+IP2JJ6eOl/V/oydti7d3slQy1drYi/cO2Cwas7aIocaOwOlSceehXI26Ofgm62sF5TvQ=
